titte: Taimur Siddiqi
logo: /assets/img/head.jpg
description: >
  <a href="https://www.kaggle.com/taimursiddiqi" target="_blank">
    
    View My Kaggle Profile
  </a>
#*description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
